name: Nouvel article
description: "Ecriture d'un nouvel article"
title: Nouvel article
labels: article
assignees: ibethus
body:
  - type: input
    id: adventure
    attributes:
      label: ":adventure:"
      description: "L'aventure liée à cet article"
      placeholder: "NC4K"
    validations:
      required: true
  - type: textarea
    id: body
    attributes:
      label: ":content:"
      description: "Le contenu de l'article"
      placeholder: "Description | Images | :gpx:"
