name: Nouvel article
description: "Ecriture d'un nouvel article"
title: Nouvel article
labels: article
assignees: ibethus
body:
  - type: textarea
    id: body
    attributes:
      label: ":content:"
      description: "Le contenu de l'article"
      validations:
        required: true
      value: |
        :adventure: //nom de l'aventure        
        :gpx: //nom du fichier gpx
