name: Nouvel article
description: "Ecriture d'un nouvel article"
title: Nouvel article
labels: article
assignees: ibethus
body:
  - type: textarea
    id: body
    validations:
        required: true
    attributes:
      description: "Le contenu de l'article"      
      value: |
        :adventure: //nom de l'aventure        
        :gpx: //nom du fichier gpx
