name: Deploy the-cyclist-diary.fr to GH Pages
run-name: Déploiement du site

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      HUGO_CACHEDIR: /tmp/hugo_cache
      HUGO_WEBPSERVER_URL: "https://webpserver.the-cyclist-diary.fr"
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'
          extended: true
      - name: Setup GH Pages
        id: pages
        uses: actions/configure-pages@v5
      - uses: whywaita/actions-cache-s3@v2
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod
          restore-keys: |
            ${{ runner.os }}-hugo-modules
          aws-s3-bucket: the-cyclist-diary-cache
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_ACCESS_KEY }}
          aws-endpoint: https://59d55d1a4dbc1f28fe6cd3d2d2036e4d.r2.cloudflarestorage.com
          aws-region: auto
          aws-s3-force-path-style: true
          aws-s3-bucket-endpoint: false
      - uses: whywaita/actions-cache-s3@v2
        with:
          path: resources
          key: ${{ runner.os }}-hugo-resources-${{ hashFiles('assets/**') }}
          restore-keys: |
            ${{ runner.os }}-hugo-resources-
          aws-s3-bucket: the-cyclist-diary-cache
          aws-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.R2_ACCESS_KEY }}
          aws-endpoint: https://59d55d1a4dbc1f28fe6cd3d2d2036e4d.r2.cloudflarestorage.com
          aws-region: auto
          aws-s3-force-path-style: true
          aws-s3-bucket-endpoint: false

      - name: Build
        run: hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Install Pagefind
        run: npx -y pagefind@latest --site public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: "https://the-cyclist-diary.fr"
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4